### ISSUE TITLE
illegal base64 data at input byte 49

### ISSUE THREAD

**Issue by nduvnjak** [danielgormly/drone-plugin-kube#10]
here is the complete Drone pipeline step where the deployment crashes:

```
  - name: k8-dev-deploy
    image: danielgormly/drone-plugin-kube:0.0.1
    pull: if-not-exists
    settings:
      template: deployment.dev.yml
      ca:
        from_secret: k8s-dev-ca
      server: https://kuber00:6443
      namespace: cutuk
      token:
        from_secret: caladrius-k8s-dev-deploy-token-nd
      config:
        from_secret: docker_credentials
    when:
      event: 
        - push
      branch:
        exclude:
          - master
```

and this is the error:

kubano v0.0.1 https://github.com/danielgormly/********-plugin-kube
2021/04/09 20:25:04 illegal base64 data at input byte 49

I wish the error provides some more detail. What is the "data at input byte 49" referring to? The .drone.yaml step, the deployment yaml used, the secret stored in Drone project, or the secret created in Kubernetes cluster?
Nevertheless I tried replacing each with some alternatives, but always getting the same error.
The very similar deployment used to work, but now it doesn't and I really can't figure out what is different now.

thanks for looking
