### ISSUE TITLE
Bug: Not applying multiple ingresses

### ISSUE THREAD

**Issue by karatekaneen** [danielgormly/drone-plugin-kube#11]
Hi,

Thanks for a great plugin!

I found an issue where I had multiple ingresses in the same yaml file and only the first was applied to the cluster, like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ whitelist }}
spec:
  tls:
  - hosts:
    - apps.company.se
    secretName: company-tls
  rules:
  - host: apps.company.se
    http:
      paths:
        - path: /app/(.*)
          # pathType: Prefix
          backend:
            serviceName: frontend-service
            servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ whitelist }}
spec:
  tls:
  - hosts:
    - apps.company.se
    secretName: company-tls
  rules:
  - host: apps.company.se
    http:
      paths:
        - path: /api/(.*)
          # pathType: Prefix
          backend:
            serviceName: backend-service
            servicePort: 80
```

I haven't had the time to test if it works with different kinds of resources but at least ingresses seems to be broken.
